"""add idempotency_key to events

Revision ID: 2bef99e94736
Revises: 83e06c1a0567
Create Date: 2026-06-10 02:11:00.656712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bef99e94736'
down_revision: Union[str, Sequence[str], None] = '83e06c1a0567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_idempotency_key'), 'events', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_idempotency_key'), table_name='events')
    op.drop_column('events', 'idempotency_key')
    # ### end Alembic commands ###
